routes:
  /essays/:
    template: essays
  /notes/:
    template: notes
  /links/:
    template: links
  /media/:
    template: media
  /photos/:
    template: photos
  /quotes/:
    template: quotes

collections:
  /:
    permalink: /{slug}/
    template: index

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
